declare module "@/layouts/side-menu"
declare module "@/base-components"
declare module "@/components/top-bar/Main"
declare module "@/components/mobile-menu/Main"
declare module "@/components/dark-mode-switcher/Main"
declare module "@/layouts/top-menu"
declare module "@/API/apiUrls"
declare module "@/Service/ApiService"
declare module "@/views/ListMenuLabels/Main"
declare module "@/views/SubMenu/Main"
declare module "@/views/ListMenu/Main"
declare module "@/views/AddMenuLabel/Main"
declare module "@/views/AddSubMenu/Main"
 
declare module "@/utils"
declare module "@/views/ListSubMenu/Main"
declare module "@/components/side-menu-tooltip/Main"
declare module "@/stores/staticData"
