import React from "react";
import { Modal, Form, Input, Button } from "antd";
import { ExclamationCircleOutlined } from "@ant-design/icons";
import Table from "../../../base-components/Table/Table";
import Supplier from "../../../Entity/Supplier";
import TableColumn from "../../../Entity/TableColumn";

const supplierColumns: TableColumn<Supplier>[] = [
  { title: "ID", dataIndex: "id" },
  { title: "Name", dataIndex: "name" },
  { title: "Address", dataIndex: "address" },
  { title: "Phone", dataIndex: "phone" },
  { title: "Email", dataIndex: "email" },
  { title: "City", dataIndex: "city" },
  { title: "State", dataIndex: "state" },
  { title: "ZIP", dataIndex: "zip" },
  { title: "Country", dataIndex: "country" },
];

const fetchSuppliers = async (): Promise<Supplier[]> => {
  return [
    {
      id: 1,
      name: "Supplier 1",
      address: "123 Main St",
      phone: "123-456-7890",
      email: "supplier1@example.com",
      city: "City A",
      state: "State A",
      zip: "12345",
      country: "Country A",
    },
    {
      id: 2,
      name: "Supplier 2",
      address: "456 Elm St",
      phone: "987-654-3210",
      email: "supplier2@example.com",
      city: "City B",
      state: "State B",
      zip: "54321",
      country: "Country B",
    },
    {
      id: 3,
      name: "Supplier 3",
      address: "789 Oak St",
      phone: "111-222-3333",
      email: "supplier3@example.com",
      city: "City C",
      state: "State C",
      zip: "67890",
      country: "Country C",
    },
    {
      id: 4,
      name: "Supplier 4",
      address: "101 Pine St",
      phone: "444-555-6666",
      email: "supplier4@example.com",
      city: "City D",
      state: "State D",
      zip: "23456",
      country: "Country D",
    },
    {
      id: 5,
      name: "oussama 5",
      address: "202 Birch St",
      phone: "777-888-9999",
      email: "supplier5@example.com",
      city: "City E",
      state: "State E",
      zip: "34567",
      country: "Country E",
    },
    {
      id: 6,
      name: "Supplier 6",
      address: "303 Cedar St",
      phone: "222-333-4444",
      email: "supplier6@example.com",
      city: "City F",
      state: "State F",
      zip: "45678",
      country: "Country F",
    },
    {
      id: 7,
      name: "Supplier 7",
      address: "404 Maple St",
      phone: "555-666-7777",
      email: "supplier7@example.com",
      city: "City G",
      state: "State G",
      zip: "56789",
      country: "Country G",
    },
    {
      id: 8,
      name: "Supplier 8",
      address: "505 Walnut St",
      phone: "888-999-0000",
      email: "supplier8@example.com",
      city: "City H",
      state: "State H",
      zip: "67891",
      country: "Country H",
    },
    {
      id: 9,
      name: "Supplier 9",
      address: "606 Chestnut St",
      phone: "333-444-5555",
      email: "supplier9@example.com",
      city: "City I",
      state: "State I",
      zip: "78901",
      country: "Country I",
    },
    {
      id: 10,
      name: "Supplier 10",
      address: "707 Willow St",
      phone: "666-777-8888",
      email: "supplier10@example.com",
      city: "City J",
      state: "State J",
      zip: "89012",
      country: "Country J",
    },
    {
      id: 11,
      name: "Supplier 11",
      address: "808 Sycamore St",
      phone: "999-000-1111",
      email: "supplier11@example.com",
      city: "City K",
      state: "State K",
      zip: "90123",
      country: "Country K",
    },
    {
      id: 12,
      name: "Supplier 12",
      address: "909 Spruce St",
      phone: "000-111-2222",
      email: "supplier12@example.com",
      city: "City L",
      state: "State L",
      zip: "01234",
      country: "Country L",
    },
    {
      id: 13,
      name: "Supplier 13",
      address: "1010 Fir St",
      phone: "111-222-3333",
      email: "supplier13@example.com",
      city: "City M",
      state: "State M",
      zip: "12345",
      country: "Country M",
    },
    {
      id: 14,
      name: "Supplier 14",
      address: "1111 Ash St",
      phone: "222-333-4444",
      email: "supplier14@example.com",
      city: "City N",
      state: "State N",
      zip: "23456",
      country: "Country N",
    },
    {
      id: 15,
      name: "Supplier 15",
      address: "1212 Poplar St",
      phone: "333-444-5555",
      email: "supplier15@example.com",
      city: "City O",
      state: "State O",
      zip: "34567",
      country: "Country O",
    },
    {
      id: 16,
      name: "Supplier 16",
      address: "1313 Redwood St",
      phone: "444-555-6666",
      email: "supplier16@example.com",
      city: "City P",
      state: "State P",
      zip: "45678",
      country: "Country P",
    },
    {
      id: 17,
      name: "Supplier 17",
      address: "1414 Pine St",
      phone: "555-666-7777",
      email: "supplier17@example.com",
      city: "City Q",
      state: "State Q",
      zip: "56789",
      country: "Country Q",
    },
    {
      id: 18,
      name: "Supplier 18",
      address: "1515 Birch St",
      phone: "666-777-8888",
      email: "supplier18@example.com",
      city: "City R",
      state: "State R",
      zip: "67890",
      country: "Country R",
    },
    {
      id: 19,
      name: "Supplier 19",
      address: "1616 Cedar St",
      phone: "777-888-9999",
      email: "supplier19@example.com",
      city: "City S",
      state: "State S",
      zip: "78901",
      country: "Country S",
    },
    {
      id: 20,
      name: "Supplier 20",
      address: "1717 Maple St",
      phone: "888-999-0000",
      email: "supplier20@example.com",
      city: "City T",
      state: "State T",
      zip: "89012",
      country: "Country T",
    },
    {
      id: 21,
      name: "Supplier 21",
      address: "1818 Walnut St",
      phone: "999-000-1111",
      email: "supplier21@example.com",
      city: "City U",
      state: "State U",
      zip: "90123",
      country: "Country U",
    },
    {
      id: 22,
      name: "Supplier 22",
      address: "1919 Chestnut St",
      phone: "000-111-2222",
      email: "supplier22@example.com",
      city: "City V",
      state: "State V",
      zip: "01234",
      country: "Country V",
    },
    {
      id: 23,
      name: "Supplier 23",
      address: "2020 Willow St",
      phone: "111-222-3333",
      email: "supplier23@example.com",
      city: "City W",
      state: "State W",
      zip: "12345",
      country: "Country W",
    },
    {
      id: 24,
      name: "Supplier 24",
      address: "2121 Sycamore St",
      phone: "222-333-4444",
      email: "supplier24@example.com",
      city: "City X",
      state: "State X",
      zip: "23456",
      country: "Country X",
    },
    {
      id: 25,
      name: "Supplier 25",
      address: "2222 Spruce St",
      phone: "333-444-5555",
      email: "supplier25@example.com",
      city: "City Y",
      state: "State Y",
      zip: "34567",
      country: "Country Y",
    },
    {
      id: 26,
      name: "Supplier 26",
      address: "2323 Fir St",
      phone: "444-555-6666",
      email: "supplier26@example.com",
      city: "City Z",
      state: "State Z",
      zip: "45678",
      country: "Country Z",
    },
    {
      id: 27,
      name: "Supplier 27",
      address: "2424 Ash St",
      phone: "555-666-7777",
      email: "supplier27@example.com",
      city: "City AA",
      state: "State AA",
      zip: "56789",
      country: "Country AA",
    },
    {
      id: 28,
      name: "Supplier 28",
      address: "2525 Poplar St",
      phone: "666-777-8888",
      email: "supplier28@example.com",
      city: "City AB",
      state: "State AB",
      zip: "67890",
      country: "Country AB",
    },
    {
      id: 29,
      name: "Supplier 29",
      address: "2626 Redwood St",
      phone: "777-888-9999",
      email: "supplier29@example.com",
      city: "City AC",
      state: "State AC",
      zip: "78901",
      country: "Country AC",
    },
    {
      id: 30,
      name: "Supplier 30",
      address: "2727 Pine St",
      phone: "888-999-0000",
      email: "supplier30@example.com",
      city: "City AD",
      state: "State AD",
      zip: "89012",
      country: "Country AD",
    },
    {
      id: 31,
      name: "Supplier 31",
      address: "2828 Birch St",
      phone: "999-000-1111",
      email: "supplier31@example.com",
      city: "City AE",
      state: "State AE",
      zip: "90123",
      country: "Country AE",
    },
    {
      id: 32,
      name: "Supplier 32",
      address: "2929 Cedar St",
      phone: "000-111-2222",
      email: "supplier32@example.com",
      city: "City AF",
      state: "State AF",
      zip: "01234",
      country: "Country AF",
    },
    {
      id: 33,
      name: "Supplier 33",
      address: "3030 Maple St",
      phone: "111-222-3333",
      email: "supplier33@example.com",
      city: "City AG",
      state: "State AG",
      zip: "12345",
      country: "Country AG",
    },
    {
      id: 34,
      name: "Supplier 34",
      address: "3131 Walnut St",
      phone: "222-333-4444",
      email: "supplier34@example.com",
      city: "City AH",
      state: "State AH",
      zip: "23456",
      country: "Country AH",
    },
    {
      id: 35,
      name: "Supplier 35",
      address: "3232 Chestnut St",
      phone: "333-444-5555",
      email: "supplier35@example.com",
      city: "City AI",
      state: "State AI",
      zip: "34567",
      country: "Country AI",
    },
    {
      id: 36,
      name: "Supplier 36",
      address: "3333 Willow St",
      phone: "444-555-6666",
      email: "supplier36@example.com",
      city: "City AJ",
      state: "State AJ",
      zip: "45678",
      country: "Country AJ",
    },
    {
      id: 37,
      name: "Supplier 37",
      address: "3434 Sycamore St",
      phone: "555-666-7777",
      email: "supplier37@example.com",
      city: "City AK",
      state: "State AK",
      zip: "56789",
      country: "Country AK",
    },
    {
      id: 38,
      name: "Supplier 38",
      address: "3535 Spruce St",
      phone: "666-777-8888",
      email: "supplier38@example.com",
      city: "City AL",
      state: "State AL",
      zip: "67890",
      country: "Country AL",
    },
    {
      id: 39,
      name: "Supplier 39",
      address: "3636 Fir St",
      phone: "777-888-9999",
      email: "supplier39@example.com",
      city: "City AM",
      state: "State AM",
      zip: "78901",
      country: "Country AM",
    },
    {
      id: 40,
      name: "Supplier 40",
      address: "3737 Ash St",
      phone: "888-999-0000",
      email: "supplier40@example.com",
      city: "City AN",
      state: "State AN",
      zip: "89012",
      country: "Country AN",
    },
    {
      id: 41,
      name: "Supplier 41",
      address: "3838 Poplar St",
      phone: "999-000-1111",
      email: "supplier41@example.com",
      city: "City AO",
      state: "State AO",
      zip: "90123",
      country: "Country AO",
    },
    {
      id: 42,
      name: "Supplier 42",
      address: "3939 Redwood St",
      phone: "000-111-2222",
      email: "supplier42@example.com",
      city: "City AP",
      state: "State AP",
      zip: "01234",
      country: "Country AP",
    },
    {
      id: 43,
      name: "Supplier 43",
      address: "4040 Pine St",
      phone: "111-222-3333",
      email: "supplier43@example.com",
      city: "City AQ",
      state: "State AQ",
      zip: "12345",
      country: "Country AQ",
    },
    {
      id: 44,
      name: "Supplier 44",
      address: "4141 Birch St",
      phone: "222-333-4444",
      email: "supplier44@example.com",
      city: "City AR",
      state: "State AR",
      zip: "23456",
      country: "Country AR",
    },
    {
      id: 45,
      name: "Supplier 45",
      address: "4242 Cedar St",
      phone: "333-444-5555",
      email: "supplier45@example.com",
      city: "City AS",
      state: "State AS",
      zip: "34567",
      country: "Country AS",
    },
    {
      id: 46,
      name: "Supplier 46",
      address: "4343 Maple St",
      phone: "444-555-6666",
      email: "supplier46@example.com",
      city: "City AT",
      state: "State AT",
      zip: "45678",
      country: "Country AT",
    },
    {
      id: 47,
      name: "Supplier 47",
      address: "4444 Walnut St",
      phone: "555-666-7777",
      email: "supplier47@example.com",
      city: "City AU",
      state: "State AU",
      zip: "56789",
      country: "Country AU",
    },
    {
      id: 48,
      name: "Supplier 48",
      address: "4545 Chestnut St",
      phone: "666-777-8888",
      email: "supplier48@example.com",
      city: "City AV",
      state: "State AV",
      zip: "67890",
      country: "Country AV",
    },
    {
      id: 49,
      name: "Supplier 49",
      address: "4646 Willow St",
      phone: "777-888-9999",
      email: "supplier49@example.com",
      city: "City AW",
      state: "State AW",
      zip: "78901",
      country: "Country AW",
    },
    {
      id: 50,
      name: "Supplier 50",
      address: "4747 Sycamore St",
      phone: "888-999-0000",
      email: "supplier50@example.com",
      city: "City AX",
      state: "State AX",
      zip: "89012",
      country: "Country AX",
    },
  ];
};

const deleteSupplier = async (id: number): Promise<void> => {
  console.log("HI deleteSupplier");
};

const editSupplier = async (supplier: Supplier): Promise<void> => {
  console.log(supplier);
};

const Main = () => {
  return (
    <>
      <div>
        <h1 className="text-2xl font-bold mb-4">List Of Supplier </h1>
      </div>
      <Table<Supplier>
        columns={supplierColumns}
        fetchData={fetchSuppliers}
        deleteData={deleteSupplier}
        editData={editSupplier}
      />
    </>
  );
};

export default Main;
