name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build React App
        run: yarn build

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Clear Docker build cache
        run: docker builder prune -a -f

      - name: Build Docker image
        run: docker build -t oussama020899/warehouseview:${{ github.sha }} --no-cache .

      - name: Publish image to Docker Hub
        run: docker push oussama020899/warehouseview:${{ github.sha }}

      - name: Publish latest tag
        run: docker tag oussama020899/warehouseview:${{ github.sha }} oussama020899/warehouseview:latest
        run: docker push oussama020899/warehouseview:latest
